//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureVerificationSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureVerificationSystem.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language:.
        /// </summary>
        public static string ChangeLanguageTextBlock {
            get {
                return ResourceManager.GetString("ChangeLanguageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add user. Please check the database. Error Message: {0}..
        /// </summary>
        public static string CheckDatabase {
            get {
                return ResourceManager.GetString("CheckDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseAppButton {
            get {
                return ResourceManager.GetString("CloseAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ComboBoxItemAdmin {
            get {
                return ResourceManager.GetString("ComboBoxItemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ControlButton {
            get {
                return ResourceManager.GetString("ControlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Time = {0}ms.
        /// </summary>
        public static string ControlTimeTextBlock {
            get {
                return ResourceManager.GetString("ControlTimeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuItemHeader {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Query Set.
        /// </summary>
        public static string EmptyQuerySet {
            get {
                return ResourceManager.GetString("EmptyQuerySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Support Set.
        /// </summary>
        public static string EmptySupportSet {
            get {
                return ResourceManager.GetString("EmptySupportSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an existing username..
        /// </summary>
        public static string EnteredExistingUsername {
            get {
                return ResourceManager.GetString("EnteredExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Class.
        /// </summary>
        public static string EstimatedClassLabel {
            get {
                return ResourceManager.GetString("EstimatedClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimaded Distances.
        /// </summary>
        public static string EstimatedDistancesLabel {
            get {
                return ResourceManager.GetString("EstimatedDistancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Register.
        /// </summary>
        public static string FailedToRegister {
            get {
                return ResourceManager.GetString("FailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that you filled up the query set..
        /// </summary>
        public static string FillUpQuerySet {
            get {
                return ResourceManager.GetString("FillUpQuerySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that you filled up the support set..
        /// </summary>
        public static string FillUpSupportSet {
            get {
                return ResourceManager.GetString("FillUpSupportSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        public static string ImageMenuItemHeader {
            get {
                return ResourceManager.GetString("ImageMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size:.
        /// </summary>
        public static string ImageSizeTextBlock {
            get {
                return ResourceManager.GetString("ImageSizeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Not Uploaded.
        /// </summary>
        public static string ImagesNotUploaded {
            get {
                return ResourceManager.GetString("ImagesNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key is incorrect..
        /// </summary>
        public static string IncorrectPrivateKey {
            get {
                return ResourceManager.GetString("IncorrectPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login as &apos;{0}&apos;..
        /// </summary>
        public static string InfoTextBlock {
            get {
                return ResourceManager.GetString("InfoTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string LanguageSettingsTextBlock {
            get {
                return ResourceManager.GetString("LanguageSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 2 images to load..
        /// </summary>
        public static string LoadTwoImages {
            get {
                return ResourceManager.GetString("LoadTwoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsersButton {
            get {
                return ResourceManager.GetString("ManageUsersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Settings.
        /// </summary>
        public static string ModelSettingsTextBlock {
            get {
                return ResourceManager.GetString("ModelSettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Classes (k):.
        /// </summary>
        public static string NumberOfClassesTextBlock {
            get {
                return ResourceManager.GetString("NumberOfClassesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKeyPasswordBox {
            get {
                return ResourceManager.GetString("PrivateKeyPasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Set.
        /// </summary>
        public static string QuerySetLabel {
            get {
                return ResourceManager.GetString("QuerySetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been added successfully..
        /// </summary>
        public static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ResultsLabel {
            get {
                return ResourceManager.GetString("ResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveAllChangesButton {
            get {
                return ResourceManager.GetString("SaveAllChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTextBlock {
            get {
                return ResourceManager.GetString("SettingsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string SortAsIDButton {
            get {
                return ResourceManager.GetString("SortAsIDButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SortAsUsernameButton {
            get {
                return ResourceManager.GetString("SortAsUsernameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Set.
        /// </summary>
        public static string SupportSetLabel {
            get {
                return ResourceManager.GetString("SupportSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Set (n):.
        /// </summary>
        public static string SupportSetTextBlock {
            get {
                return ResourceManager.GetString("SupportSetTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameTextBox {
            get {
                return ResourceManager.GetString("UsernameTextBox", resourceCulture);
            }
        }
    }
}
